
export const GET_MARVEL_CHARACTERS_REQ = "GET_MARVERL_CHACTERS_REQ"
export const GET_MARVEL_CHARACTERS_SUCCESS = "GET_MARVEL_CHARACTERS_SUCCESS"
export const GET_MARVEL_CHARACTERS_ERROR = "GET_MARVEL_CHARACTERS_ERROR"
